# Generated by Django 3.0.8 on 2020-07-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('BLACK', 'Black'), ('WHITE', 'White')], max_length=5)),
                ('breed', models.CharField(choices=[('PS', 'Persian'), ('BC', 'Bengal'), ('SM', 'Siamese'), ('RD', 'Ragdoll')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('BLACK', 'Black'), ('WHITE', 'White')], max_length=5)),
                ('breed', models.CharField(choices=[('GS', 'German Shepherd'), ('BD', 'Bulldog'), ('PD', 'Poodle'), ('GD', 'Golden Retriever'), ('BG', 'Beagle'), ('CH', 'Chihuahua')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('BLACK', 'Black'), ('WHITE', 'White')], max_length=5)),
                ('breed', models.CharField(choices=[('K', 'Koi'), ('O', 'Oranda'), ('C', 'Comet'), ('BT', 'Black Telescope'), ('F', 'Fantail')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
